# SPDX-FileCopyrightText: 2023 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: LicenseRef-COMCAST
---
name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:
  
jobs:
  ci:
    uses: xmidt-org/shared-go/.github/workflows/ci.yml@5268009a77dc4857b9ced4b123cd2c3432ec4c58 # v4.9.7
    with:
      release-type:         program
      release-main-package: ./cmd/eventstream
      release-docker-file:  .release/Dockerfile
      release-docker:        true
      release-docker-latest: true
      release-docker-major:  true
      release-docker-minor:  true
      release-arch-arm64:    true
      release-arch-amd64:    true
      sonarcloud-exclusions: '**/*_test.go,**/vendor/**,**/mock.go,**/*_module.go,**/public_key_provider.go'
    secrets: inherit
  
      
