# SPDX-FileCopyrightText: 2023 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: LicenseRef-COMCAST
---
name: 'PROJ: xmidt-team'

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    uses: comcast-cl/shared-project/.github/workflows/proj.yml@573f0133683e7e2dfccacb4d2c43055ed91cee87 # v1.0.71
    with:
      project-number: 3
    secrets: inherit
